branch-defaults:
  primary:
    environment: TubeFriends-production
environment-defaults:
  TubeFriends-production:
    branch: null
    repository: null
global:
  application_name: Tube-Friends
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Node.js running
    on 64bit Amazon Linux/4.8.1
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
