export const ACTIVATE_LOGIN_PAGE = 'ACTIVATE_LOGIN_PAGE';
export const DEACTIVATE_LOGIN_PAGE = 'DEACTIVATE_LOGIN_PAGE';

export const FETCH_CATEGORIES_COMPLETE = 'FETCH_CATEGORIES_COMPLETE';
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR';

export const FETCH_STORIES_COMPLETE = 'FETCH_STORIES_COMPLETE';
export const FETCH_STORIES_ERROR = 'FETCH_STORIES_ERROR';
export const FETCH_STORIES_REQUESTED = 'FETCH_STORIES_REQUESTED';

export const LIKE_TOGGLE_COMPLETE = 'LIKE_TOGGLE_COMPLETE';
export const LIKE_TOGGLE_REQUESTED = 'LIKE_TOGGLE_REQUESTED';

export const LOG_IN_REQUESTED = 'LOG_IN_REQUESTED';
export const LOG_IN_COMPLETE = 'LOG_IN_COMPLETE';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';

export const LOG_OUT_COMPLETE = 'LOG_OUT_COMPLETE';

export const SEARCH_STORIES_COMPLETE = 'SEARCH_STORIES_COMPLETE';

export const TOGGLE_MENU = 'TOGGLE_MENU';
export const TOGGLE_PROFILE = 'TOGGLE_PROFILE';
